#include<stdio.h>
void NhapMang1Chieu(int a[],int n)
{
	int i;
	for(i = 0;i < n;i++)
	{
	printf("Nhap vao so a thu %d: ",i + 1);
	scanf("%d",&a[i]);
	}
}
void inMang1Chieu(int a[],int n)
{
	int i;
	printf("Mang vua nhap la: ");
	for(i = 0;i < n;i++)
		printf("%d ",a[i]);
}

void NhapMang2Chieu(int b[][50], int n, int m)
{
	int i,j;
	for(i = 0; i < n; i++)
	{
		for(j = 0;j < m;j++)
		{
			printf("\nb[%d,%d]: ",i + 1 ,j + 1);
			scanf("%d",&b[i][j]);
		}
	}
}
void inMang2Chieu(int b[][50], int n, int m)
{
	int i,j;
	for(i = 0; i < n; i++)
	{
		for(j = 0;j < m;j++)
		{
			printf(" %d ",b[i][j]);
			printf(" ");
		}
		printf("\n");
	}
}
			
int TimMax(int a[],int n)
{
	int i, max = a[0];
	for(i = 0;i < n;i++)
	{
		if(max < a[i])
			max = a[i];
	}
	return max;
}

int SoDuong(int a[], int n)
{
	int i,demduong = 0;
	for(i = 0;i < n;i++)
	{
		if(a[i] > 0)
			demduong++;
	}
	return demduong;
}

int TimSoChan(int b[][50],int n,int m)
{
	int i,j,sochan = 0;
	for(i = 0; i < n; i++)
		for(j = 0;j < m;j++)
			if(b[i][j] % 2 == 0 )
				sochan = sochan + 1;	
	return sochan;
}
	
int main()
{
	int a[50],n,b[50][50],m;
	do
	{
		printf("Nhap n: ");
		scanf("%d",&n);
	}
	while(n < 0 || n > 50);	
	do
	{
		printf("\nNhap m: ");
		scanf("%d",&m);
	}
	while(n < 0 || n > 50);	
	NhapMang1Chieu(a, n);
	inMang1Chieu(a, n);
	printf("\nMax: %d",TimMax(a, n));
	printf("\nCo %d so duong trong mang.",SoDuong(a, n));
	NhapMang2Chieu(b, n, m);
	inMang2Chieu(b, n, m);
	printf("Co %d so chan trong mang.", TimSoChan(b, n, m));
}

